INSTALL_TARGET_PROCESSES = WhatsApp
THEOS_DEVICE_IP = 192.168.0.105

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WASilentBadges

WASilentBadges_FILES = Tweak.xm
WASilentBadges_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
