INSTALL_TARGET_PROCESSES = SpringBoard
THEOS_DEVICE_IP = 192.168.0.101
# ARCH = 

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = grinderImage

grinderImage_FILES = Tweak.x
grinderImage_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
